export const placeholderAccounts = [
  {
    id: "acc_123",
    availableBalance: 1500.75,
    currentBalance: 1800.5,
    officialName: "Checking Account",
    mask: "1234",
    institutionId: "inst_001",
    name: "Primary Checking",
    type: "depository",
    subtype: "checking",
    appwriteItemId: "item_123",
    shareableId: "share_123",
  },
  {
    id: "acc_456",
    availableBalance: 5000.0,
    currentBalance: 5200.0,
    officialName: "Savings Account",
    mask: "5678",
    institutionId: "inst_002",
    name: "Emergency Savings",
    type: "depository",
    subtype: "savings",
    appwriteItemId: "item_456",
    shareableId: "share_456",
  },
  {
    id: "acc_789",
    availableBalance: 200.0,
    currentBalance: 250.0,
    officialName: "Credit Card",
    mask: "9876",
    institutionId: "inst_003",
    name: "Rewards Credit",
    type: "credit",
    subtype: "credit card",
    appwriteItemId: "item_789",
    shareableId: "share_789",
  },
];
